//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilieLaissBackend.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaItemFacet
    {
        public long ID { get; set; }
        public long ID_MediaItem { get; set; }
        public long ID_FacetValue { get; set; }
    
        public virtual FacetValue FacetValue { get; set; }
        public virtual MediaItem MediaItem { get; set; }
    }
}
