//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilieLaissBackend.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaItemFacet
    {
        public long ID { get; set; }
        public long ID_MediaItem { get; set; }
        public long ID_FacetValue { get; set; }
    
        public virtual FacetValue FacetValue { get; set; }
        public virtual MediaItem MediaItem { get; set; }
    }
}
