//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilieLaissBackend.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MediaItem()
        {
            this.MediaItemFacets = new HashSet<MediaItemFacet>();
        }
    
        public long ID { get; set; }
        public long ID_Group { get; set; }
        public byte Type { get; set; }
        public string NameGerman { get; set; }
        public string NameEnglish { get; set; }
        public string DescriptionGerman { get; set; }
        public string DescriptionEnglish { get; set; }
        public bool OnlyFamily { get; set; }
        public System.DateTimeOffset CreateDate { get; set; }
        public Nullable<long> ID_UploadPicture { get; set; }
        public Nullable<long> ID_UploadVideo { get; set; }
    
        public virtual MediaGroup MediaGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaItemFacet> MediaItemFacets { get; set; }
        public virtual UploadPictureItem UploadPictures { get; set; }
        public virtual UploadVideoItem UploadVideoItems { get; set; }
    }
}
