//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilieLaissBackend.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadVideoItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UploadVideoItem()
        {
            this.MediaItems = new HashSet<MediaItem>();
        }
    
        public long ID { get; set; }
        public string OriginalName { get; set; }
        public byte Status { get; set; }
        public System.DateTimeOffset UploadDate { get; set; }
        public int OriginalHeight { get; set; }
        public int OriginalWidth { get; set; }
        public int DurationHour { get; set; }
        public int DurationMinute { get; set; }
        public int DurationSecond { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaItem> MediaItems { get; set; }
    }
}
