//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilieLaissBackend.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadPictureItemExif
    {
        public long ID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<double> Resolution_X { get; set; }
        public Nullable<double> Resolution_Y { get; set; }
        public string Resolution_Unit { get; set; }
        public Nullable<short> Orientation { get; set; }
        public Nullable<System.DateTimeOffset> DDL_Recorded { get; set; }
        public Nullable<double> Exposure_Time { get; set; }
        public Nullable<short> Exposure_Programm { get; set; }
        public Nullable<short> Exposure_Mode { get; set; }
        public Nullable<double> F_Number { get; set; }
        public Nullable<int> ISO_Sensitivity { get; set; }
        public Nullable<double> Shutter_Speed { get; set; }
        public Nullable<short> Metering_Mode { get; set; }
        public Nullable<int> Flash_Mode { get; set; }
        public Nullable<double> Focal_Length { get; set; }
        public Nullable<short> Sensing_Mode { get; set; }
        public Nullable<short> White_Balance_Mode { get; set; }
        public Nullable<short> Sharpness { get; set; }
        public System.Data.Entity.Spatial.DbGeography GPS_Location { get; set; }
    
        public virtual UploadPictureItem UploadPicture { get; set; }
    }
}
