//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilieLaissBackend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mail_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mail_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FamilieLaissBackend.Resources.Mail_Resources", typeof(Mail_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Anrede_Prefix_Men {
            get {
                return ResourceManager.GetString("Anrede_Prefix_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Anrede_Prefix_Women {
            get {
                return ResourceManager.GetString("Anrede_Prefix_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification from Familie - Laiss.
        /// </summary>
        public static string FamilieLaiss_Notification {
            get {
                return ResourceManager.GetString("FamilieLaiss_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Familie - Laiss.
        /// </summary>
        public static string Label_Visit {
            get {
                return ResourceManager.GetString("Label_Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an automatically generated eMail. Please do not reply to this eMail..
        /// </summary>
        public static string Not_Reply {
            get {
                return ResourceManager.GetString("Not_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string Rights_Reserved {
            get {
                return ResourceManager.GetString("Rights_Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Facebook.
        /// </summary>
        public static string Share_Facebook {
            get {
                return ResourceManager.GetString("Share_Facebook", resourceCulture);
            }
        }
    }
}
