//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilieLaissBackend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PasswordResetToken_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasswordResetToken_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FamilieLaissBackend.Resources.PasswordResetToken_Resources", typeof(PasswordResetToken_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string Click_1 {
            get {
                return ResourceManager.GetString("Click_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Click_2 {
            get {
                return ResourceManager.GetString("Click_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to enter a new password for your account..
        /// </summary>
        public static string Click_3 {
            get {
                return ResourceManager.GetString("Click_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested a new password for &quot;Familie - Laiss&quot;..
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while sending the mail with instructions how you reset your Password. Please contact your administrator..
        /// </summary>
        public static string Mail_Error {
            get {
                return ResourceManager.GetString("Mail_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password for &quot;Familie - Laiss&quot;.
        /// </summary>
        public static string Mail_Subject {
            get {
                return ResourceManager.GetString("Mail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account could be found for given eMail-Adress..
        /// </summary>
        public static string Wrong_Mail {
            get {
                return ResourceManager.GetString("Wrong_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security question or your security answer is wrong..
        /// </summary>
        public static string Wrong_Security {
            get {
                return ResourceManager.GetString("Wrong_Security", resourceCulture);
            }
        }
    }
}
