//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilieLaissBackend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityQuestion_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityQuestion_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FamilieLaissBackend.Resources.SecurityQuestion_Resources", typeof(SecurityQuestion_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the maiden name of your mother ?.
        /// </summary>
        public static string Question_1 {
            get {
                return ResourceManager.GetString("Question_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the name of the first CD you have bought ?.
        /// </summary>
        public static string Question_10 {
            get {
                return ResourceManager.GetString("Question_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the name of your primary school ?.
        /// </summary>
        public static string Question_2 {
            get {
                return ResourceManager.GetString("Question_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which movie have you seen in cinema first ?.
        /// </summary>
        public static string Question_3 {
            get {
                return ResourceManager.GetString("Question_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of your favorite Uncle ?.
        /// </summary>
        public static string Question_4 {
            get {
                return ResourceManager.GetString("Question_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where did you spend your honeymoon ?.
        /// </summary>
        public static string Question_5 {
            get {
                return ResourceManager.GetString("Question_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the name of your first pet ?.
        /// </summary>
        public static string Question_6 {
            get {
                return ResourceManager.GetString("Question_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was your first car ?.
        /// </summary>
        public static string Question_7 {
            get {
                return ResourceManager.GetString("Question_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was your childhood nickname  ?.
        /// </summary>
        public static string Question_8 {
            get {
                return ResourceManager.GetString("Question_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what year was your father born ?.
        /// </summary>
        public static string Question_9 {
            get {
                return ResourceManager.GetString("Question_9", resourceCulture);
            }
        }
    }
}
