//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilieLaissBackend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UnlockAccountMail_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnlockAccountMail_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FamilieLaissBackend.Resources.UnlockAccountMail_Resources", typeof(UnlockAccountMail_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked by the administrator. From this moment on you can not log on to our website..
        /// </summary>
        public static string Account_Locked {
            get {
                return ResourceManager.GetString("Account_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been enabled by the administrator. You can now login with no restrictions on our site..
        /// </summary>
        public static string Account_Unlocked {
            get {
                return ResourceManager.GetString("Account_Unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked.
        /// </summary>
        public static string Header_Lock {
            get {
                return ResourceManager.GetString("Header_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock account.
        /// </summary>
        public static string Header_Unlock {
            get {
                return ResourceManager.GetString("Header_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have questions about this process then please be happy to contact our support team..
        /// </summary>
        public static string Information_Locked {
            get {
                return ResourceManager.GetString("Information_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you enjoy browsing through our website..
        /// </summary>
        public static string Information_Unlocked {
            get {
                return ResourceManager.GetString("Information_Unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been locked for &quot;Familie - Laiss&quot;.
        /// </summary>
        public static string Mail_Subject_Lock {
            get {
                return ResourceManager.GetString("Mail_Subject_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been unlocked for &quot;Familie - Laiss&quot;.
        /// </summary>
        public static string Mail_Subject_Unlock {
            get {
                return ResourceManager.GetString("Mail_Subject_Unlock", resourceCulture);
            }
        }
    }
}
