//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilieLaissIdentity.Models.Account.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegisterViewModel_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterViewModel_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FamilieLaissIdentity.Models.Account.Resources.RegisterViewModel_Resources", typeof(RegisterViewModel_Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City_Display {
            get {
                return ResourceManager.GetString("City_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required.
        /// </summary>
        public static string City_Required {
            get {
                return ResourceManager.GetString("City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country_Display {
            get {
                return ResourceManager.GetString("Country_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-Adress.
        /// </summary>
        public static string Email_Display {
            get {
                return ResourceManager.GetString("Email_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-Adress is required.
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid Email-Adress. For example: mail.test@test.com.
        /// </summary>
        public static string Email_Valid {
            get {
                return ResourceManager.GetString("Email_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familyname.
        /// </summary>
        public static string FamilyName_Display {
            get {
                return ResourceManager.GetString("FamilyName_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familyname is required.
        /// </summary>
        public static string FamilyName_Required {
            get {
                return ResourceManager.GetString("FamilyName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string FirstName_Display {
            get {
                return ResourceManager.GetString("FirstName_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname is required.
        /// </summary>
        public static string FirstName_Required {
            get {
                return ResourceManager.GetString("FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender_Display {
            get {
                return ResourceManager.GetString("Gender_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at max {1} characters long.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House number.
        /// </summary>
        public static string Number_Display {
            get {
                return ResourceManager.GetString("Number_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House number is required.
        /// </summary>
        public static string Number_Required {
            get {
                return ResourceManager.GetString("Number_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password_Display {
            get {
                return ResourceManager.GetString("Password_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        public static string PasswordConfirm_Display {
            get {
                return ResourceManager.GetString("PasswordConfirm_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string PasswordConfirm_Match {
            get {
                return ResourceManager.GetString("PasswordConfirm_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street_Display {
            get {
                return ResourceManager.GetString("Street_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street is required.
        /// </summary>
        public static string Street_Required {
            get {
                return ResourceManager.GetString("Street_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName_Display {
            get {
                return ResourceManager.GetString("UserName_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UserName_Required {
            get {
                return ResourceManager.GetString("UserName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP-Code.
        /// </summary>
        public static string ZIP_Display {
            get {
                return ResourceManager.GetString("ZIP_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP-Code is required.
        /// </summary>
        public static string ZIP_Required {
            get {
                return ResourceManager.GetString("ZIP_Required", resourceCulture);
            }
        }
    }
}
